theme: jekyll-theme-minimal
title: Aishwarya H. Balwani
logo: /images/lab-bday-selfie-filter-crop.jpg
description: Postdoctoral Research Associate, Department of Developmental Neurobiology @St. Jude Children's Research Hospital
show_downloads: false
